### ISSUE TITLE
Knowledge management

### ISSUE THREAD

**Issue by kev-ngo** [Web3-API/dao#143]
## Issue
Web3API DAO's knowledge and information is in disparate places.  Some examples:
- Notion for meeting notes
- Github for proposals; Snapshot for proposal voting; Aragon for proposal submissions
- Google sheets for operating model
- Information getting lost in Discord
- External communications using Airtable

## Proposed solution
Have a central hub that points to various information.  A good platform could be **Discourse**.  See below for how this could look like:
	
![W3 Knowledge Mgmt](https://user-images.githubusercontent.com/69411313/117606957-d3bdf700-b10f-11eb-9833-a27e6535a88e.jpg)

## Misc. resources
**[Knowledge management (from Wikipedia)](https://en.wikipedia.org/wiki/Knowledge_management)** is the process of creating, sharing, using and managing the knowledge and information of an organization.

**Comment by dOrgJelli** [comment]
Looks fantastic

**Comment by dOrgJelli** [comment]
We have a dicourse setup, DM for info & and I can give you admin

**Comment by orishim** [comment]
This looks great! It would be good to validate/inform this approach with some existing examples of other communities that have achieved similar knowledge management using Discourse. 

Here are some that I know of:
- https://forum.sushi.com/
- https://forum.pokt.network/
- https://research.lido.fi/
- https://forum.badger.finance/
- https://gov.yearn.finance/

**Comment by kev-ngo** [comment]
See link: [**Updated Web3API DAO Discourse**](https://forum.web3api.dev/).

It still needs work but I'll close the issue now since this will be on-going maintainence thing.
