### ISSUE TITLE
Builders needed : (Devtools, WASM, Typescript)

### ISSUE THREAD

**Issue by rihp** [Web3-API/dao#18]
How many devs do we need?

**Comment by rihp** [comment]
Although this is explained in the DAO one pager, we could have a more comprehensive page to onboard builders, or a short video that covers this topic.

**Comment by dOrgJelli** [comment]
I think we should have this as a sub-folder in the DAO repo. That way we can add new role descriptions the DAO is looking to hire for there. Maybe call the folder "help-wanted" and have documents like `core-developer.md`

**Comment by rihp** [comment]
```
![](./logo/Web3API_On_Black_BG.jpg)  

# Contributing to the Web3API standard

The Web3API Standard makes integrating Web3 protocols quick and seamless without sacrificing decentralization. Learn about the project [here](https://web3api.dev).

We're looking for experienced developers to build Web3. You are a good fit if you have proven experience with:
- WASM 
- Typescript
- Developer Tools
- GraphQL
- Solidity

If would like to contribute, please contact:
-
-
```

**Comment by dOrgJelli** [comment]
Looks like a great start @rihp, thank you! Iterating on this here: https://github.com/Web3-API/dao/blob/recruiting/help-wanted/core-developer.md

**Comment by rihp** [comment]
Awesome, moving conversation to #78
