### ISSUE TITLE
Improving user funnels and onboarding Experience

### ISSUE THREAD

**Issue by rihp** [Web3-API/dao#37]
Right now the user funnels are sketched and can be reevaluated.

Working on clearly defined steps from first encounter with the Web3API brand to an active user (Partner/Builder/Funder) will help the Web3API project grow in a sustainable fashion that avoids diffusion of effort, and leverages all possible user attention.

**Comment by rihp** [comment]
This issue should be broken down to smaller issues. 
This is a birds eye view of the current funnel, with improvement suggestions. PM me for link to Figma board
![funnels alpha](https://user-images.githubusercontent.com/12145726/99882024-be1a4b00-2c1d-11eb-81fb-f1a02cae06bd.png)

**Comment by blackboxlaw** [comment]
I can begin work on this one. I have a good level of experience from each perspective, Funder Builder and Partner.  I will flow-chart it first with a basic design layout and then submit it for general comments. If the team likes the structure I will make a proposal for some Web3API tokens using a standardized template to help document the workflow for future FBPs.

**Comment by rihp** [comment]
I would focus on one funnel at a time, and recommend tackling specifically the builder's perspective as it's the one that will have the most short and long term impact. 

For example, a builder's FAQ is something that could improve the builder's onboarding experience

**Comment by blackboxlaw** [comment]
I will focus on the Builder's section first.  I also will create a graphic that will have the other columns be filled in later and the content will be separate from the graphic.

**Comment by rihp** [comment]
To save time I can add you to the Figma board from which the above graphic was generated.

**Comment by blackboxlaw** [comment]
yes add me to Figma. 
I have used  Lucidchart for a few years and most do most flow charting there, but I will grab elements from whatever Figma charts you want to add me to.

**Comment by PhilH** [comment]
> This issue should be broken down to smaller issues.
> This is a birds eye view of the current funnel, with improvement suggestions. PM me for link to Figma board

Indeed, I'm going to create a smaller issue dedicated to providing written guidance to open source contributors joining the project 🙂

**Comment by tenfinney** [comment]
Developing incentives to participate in a Web3API Squad can help newly interested builders to both onboard and become active participants quickly.  
Will track with issue #62.

**Comment by rihp** [comment]
Drafting around this topic started on the following branch:

 https://github.com/Web3-API/dao/tree/squad-roadmap-integration/

**Comment by dOrgJelli** [comment]
Closing this for now, feel free to reopen if you feel there is work here that hasn't been explored / completed.
