### ISSUE TITLE
First App Live: Web3API IDE

### ISSUE THREAD

**Issue by rihp** [Web3-API/dao#45]
This is part of the Q4 2020 OKRs.
Which are the potential candidate apps that could go live by EOY? @dOrgJelli @cbrzn @Remscar @orishim

**Comment by dOrgJelli** [comment]
Two demo applications I'd love to see (and am planning on creating) are:
- Simple Storage
- Web3API IDE ([GraphiQL](https://graphql.org/swapi-graphql) Fork)

**Comment by rihp** [comment]
Awesome, since we only need to have one App live by EOY, I think the Web3API IDE might be the most rewarding for the Web3API project. 

If you agree, we can make this issue more specific -> **First App Live: Web3API IDE**

**Comment by dOrgJelli** [comment]
Yes that sounds good. We'll also need to have a Web3API live for the app to query, so we can just use the SimpleStorage Web3API that's already created, and publish it to a testnet like rinkeby.

**Comment by rihp** [comment]
> We'll also need to have a Web3API live
Let's track that in issue #44

**Comment by rihp** [comment]
milestone moved to the roadmap repo here :  https://github.com/Web3-API/roadmap/issues/2
