### ISSUE TITLE
Add a Solution section to landingpage

### ISSUE THREAD

**Issue by rihp** [Web3-API/dao#57]
Continuation from issue #32

**Comment by rihp** [comment]
Initial mockups and copy here:

https://docs.google.com/document/d/137gJxC8VtMdmLS6fI2ZNp6d2dFVif68fb8_CBytKWCc/edit?usp=sharing

theres a link there to describe the animation
maybe the animation can be something different though. 

An animation like what's mentioned there costs ~200 USD to get done

**Comment by dOrgJelli** [comment]
Implemented here: https://github.com/Web3-API/landing-page/pull/45
