### ISSUE TITLE
Security: Add DMARC security to web3api.dev

### ISSUE THREAD

**Issue by dOrgJelli** [Web3-API/dao#94]
In order to prevent spoof emails coming from "web3api.dev", we should add DMARC record to our domain. More information here: https://support.google.com/a/answer/2466580?hl=en&ref_topic=2759254

**Comment by raza54022** [comment]
DMARC record isn’t enough. Please use hardfail(-) inorder to protect you completely.

**Comment by raza54022** [comment]
Dorg! pay whatever you want but please don't do injustice to me

**Comment by raza54022** [comment]
Dorg this is Alex. Please pay whatever you want for my all reported vulnerabilities but please don't do injustice to me

**Comment by dOrgJelli** [comment]
Fixed
